### ISSUE TITLE
Hangs while attempting to connect to Discord 

### ISSUE THREAD

**Issue by HIDEN64** [CamK06/Discord-IRC-Sharp#1]
The bot hangs when attempting to connect to Discord... specifically at this point:

![image](https://user-images.githubusercontent.com/74623886/188249885-94433a1e-df63-4b0f-844d-171381184493.png)

It definitely is connecting to Discord, just not doing anything... for some reason... as shown here:

![image](https://user-images.githubusercontent.com/74623886/188249918-352b660b-7879-452c-9d37-58f2a1010904.png)

OS: Windows Server 2012 R2 (Windows 8.1)
Framework: .NET 6.0
Attempted troubleshooting: reseting the bot token, recompiling the source code, rewriting the config.json file

**Comment by dkay0670** [comment]
windows issue

**Comment by RoscoeDaWah** [comment]
did you enable the message content intent

**Comment by HIDEN64** [comment]
Yes.

**Comment by RoscoeDaWah** [comment]
wait, why are you running the dll with dotnet

**Comment by RoscoeDaWah** [comment]
did you build this on Windows or Linux?

**Comment by RoscoeDaWah** [comment]
wait nvm

maybe try `dotnet run` from the csircrelay folder

**Comment by HIDEN64** [comment]
> wait, why are you running the dll with dotnet

No particular reason. Same thing happens when running it through the .exe.

> did you build this on Windows or Linux?

Windows.

> maybe try dotnet run from the csircrelay folder

From my memory, this had the same result.

**Comment by HIDEN64** [comment]
Closing. Appears to be some weird quirk when running on older Windows (pre-Windows 10) which isn't related to this project-but moreso Discord.NET. Runs fine under Linux and i'm pretty sure modern Windows too.
